import type { Metadata } from "next";
import Head from 'next/head';
import "./globals.css";
import Footer from "@/components/Footer";
import NavBar from "@/components/NavBar";
import AlertSection from "@/components/alert-section";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`bg-background antialiased`}
      >
        <div>
          <Head>
            <title>The NYC Optometrist</title>
            <meta name="description" content="Your vision is our mission at The NYC Optometrist. We provide comprehensive eye care services." />
            <meta name="robots" content="index, follow" />
            <link rel="canonical" href="https://www.thenycoptometrist.com" />
          </Head>
          <div className="">
          <div className="w-screen z-[100]">
          <AlertSection />
          <NavBar />
          </div>
          <main className="">
            {children}
          </main>
          <Footer />
          </div>
        </div>
      </body>
    </html>
  );
}
