/**
 * Centralized review statistics
 *
 * This file is auto-generated by scripts/convert-zocdoc-to-website-format.js
 * DO NOT EDIT MANUALLY - run the conversion script to update these values
 *
 * Usage:
 *   import { REVIEW_STATS } from '@/lib/review-stats';
 *   console.log(REVIEW_STATS.averageRating); // "4.92"
 *   console.log(REVIEW_STATS.totalReviews);  // 49
 */

export const REVIEW_STATS = {
  /** Average rating from all ZocDoc reviews (e.g., "4.92") */
  averageRating: "4.92",

  /** Average rating as a number for calculations */
  ratingValue: 4.92,

  /** Total number of reviews on ZocDoc */
  totalReviews: 49,

  /** Number of reviews with written text (displayable) */
  reviewsWithText: 23,

  /** Rating distribution */
  ratingDistribution: {
    fiveStars: 48,
    fourStars: 0,
    threeStars: 0,
    twoStars: 0,
    oneStar: 1,
  },

  /** Last updated timestamp */
  lastUpdated: "2025-11-27",

  /** Source of the reviews */
  source: "ZocDoc" as const,
} as const;

/** Type for the review stats object */
export type ReviewStats = typeof REVIEW_STATS;
